# coding: utf-8

"""
    User Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_delete_by_id(self) -> None:
        """Test case for delete_by_id

        Delete an existing user by ID
        """
        pass

    def test_find_all(self) -> None:
        """Test case for find_all

        Find all existing users
        """
        pass

    def test_find_by_id(self) -> None:
        """Test case for find_by_id

        Find an existing user by ID
        """
        pass

    def test_save_by_id(self) -> None:
        """Test case for save_by_id

        Update an existing user by ID
        """
        pass

    def test_save_new(self) -> None:
        """Test case for save_new

        Create a new user
        """
        pass


if __name__ == '__main__':
    unittest.main()
