# coding: utf-8

"""
    User Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.new_user import NewUser

class TestNewUser(unittest.TestCase):
    """NewUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewUser:
        """Test NewUser
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewUser`
        """
        model = NewUser()
        if include_optional:
            return NewUser(
                id = '',
                username = '',
                given_name = '',
                family_name = '',
                address = '',
                password = ''
            )
        else:
            return NewUser(
                username = '',
                given_name = '',
                family_name = '',
                address = '',
                password = '',
        )
        """

    def testNewUser(self):
        """Test NewUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
